from protozoo.impl_pytorch import create_loss_input
from protozoo.impl_pytorch import create_model_input
from protozoo.impl_pytorch import loss_class
from protozoo.impl_pytorch import optimizer_class
